
## POST Add an item in Gallery
# POST http://localhost:5000/api/gallery
# Content-Type: application/json

# {
#   "label": "Classroom Collaboration",
#   "src": "/images/Gallery/1.jpg",
#   "desc": "A vibrant classroom session at Glamour Institute, showcasing student collaboration and creativity."
# }




### Get all  Gallery Items
# GET http://localhost:5000/api/gallery





## PUT update an item in gallery
# PUT  http://localhost:5000/api/gallery
# Content-Type: application/json

# {
#   "id": "683e8fafe0832009480f4964",
#   "label": "Updated Gallery Item",
#   "src": "/images/Gallery/4.jpg",
#   "desc": "An updated description for the gallery item, showcasing the latest features and improvements."
# }



## Delete an item from Gallery
# DELETE  http://localhost:5000/api/gallery
# Content-Type: application/json

# {
#   "id": "683e8f6ae0832009480f4962"
# }